name: AUTO_LGTM

on:
  pull_request:
    types:
      - opened

jobs:
  looks_good_to_me:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: LGTM Comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          pullRequestOpenedReactions: "hooray, +1"
          pullRequestOpenedComment: LGTM
      - name: Merge PR
	uses: devmasx/merge-branch@master
	with:
	  github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          label_name: 'LGTM'
          target_branch: 'develop'
